Models/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long id { get; set; }
        public long CarId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public long StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ServiceStation.Models;
using ServiceStation.SomeBusinessLogic;
using ServiceStation.ViewModels;

namespace ServiceStation.Controllers
{
    public class ClientsController : Controller
    {
        private ServiceStationEntities db = new ServiceStationEntities();

        public ActionResult Index()
        {
            var viewModel = new ClientsIndex() { Clients = db.Clients.ToList() };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(ClientsIndex viewModel)
        {
            viewModel.Clients = DbSearcher.SearchClients(db, viewModel.Filter);
            return View(viewModel);
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,FirstName,LastName,DateOfBirth,Address,Phone,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,FirstName,LastName,DateOfBirth,Address,Phone,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            var canDelete = client.Cars.Count == 0;
            return View(new Tuple<Client, bool>(client, canDelete));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Client client = db.Clients.Find(id);
            if (client.Cars.Count == 0)
            {
                db.Clients.Remove(client);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ServiceStation.Models;

namespace ServiceStation.Controllers
{
    public class OrdersController : Controller
    {
        private ServiceStationEntities db = new ServiceStationEntities();
        
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        
        public ActionResult Create(long? clientId, long? carId)
        {

            if (carId == null)
            {
                ViewBag.CarId = clientId == null ? new SelectList(db.Cars, "id", "VIN") :
                    new SelectList(db.Cars.Where(c => c.ClientId == clientId), "id", "VIN");
                ViewBag.ClientId = clientId;
            }
            else
            {
                ViewBag.CarSelected = true;
                ViewBag.CarId = carId;
            }
            ViewBag.StatusId = new SelectList(db.OrderStatuses, "id", "Status");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,CarId,Date,Amount,StatusId")] Order order)
        {
            if (TempData["CarId"] != null)
                order.CarId = (long)TempData["CarId"];

            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Details", "Cars", new { id = order.CarId });
            }

            ViewBag.CarId = new SelectList(db.Cars, "id", "VIN", order.CarId);
            ViewBag.StatusId = new SelectList(db.OrderStatuses, "id", "Status", order.StatusId);
            return View(order);
        }
        
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarId = new SelectList(db.Cars, "id", "VIN", order.CarId);
            ViewBag.StatusId = new SelectList(db.OrderStatuses, "id", "Status", order.StatusId);
            return View(order);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,CarId,Date,Amount,StatusId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Cars", new { id = order.CarId });
            }
            ViewBag.CarId = new SelectList(db.Cars, "id", "VIN", order.CarId);
            ViewBag.StatusId = new SelectList(db.OrderStatuses, "id", "Status", order.StatusId);
            return View(order);
        }
        
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Details", "Cars", new { id = order.CarId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Orders/Create.cshtml
@model ServiceStation.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (ViewBag.CarSelected == null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.CarId, "Car VIN", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CarId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CarId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", id = "datetimepicker1" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                    format: 'D MMM YYYY'
                });
            });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @(ViewBag.ClientId == null ?
            ViewBag.CarId == null || ViewBag.CarId.GetType().Name != "long" ?
            Html.ActionLink("Back to List", "Index", "Clients") :
            Html.ActionLink("Back to List", "Details", "Cars", new { id = ViewBag.CarId }, null) :
        Html.ActionLink("Back to List", "Details", "Clients", new { id = ViewBag.ClientId }, null))
</div>
@{
    if (ViewBag.CarSelected != null)
    {
        TempData["CarId"] = ViewBag.CarId;
    }
}

@section Scripts {
    @Styles.Render("~/Content/bootstrap-datetimepicker.css")
    @Scripts.Render("~/scripts/moment.min.js")
    @Scripts.Render("~/scripts/bootstrap-datetimepicker.min.js")
}

Views/Orders/Delete.cshtml
@model ServiceStation.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Car.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderStatus.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderStatus.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Clients", new { id = Model.Car.ClientId }, null)
        </div>
    }
</div>

Views/Orders/Details.cshtml
@model ServiceStation.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <div class="row">
        <div class="col-xs-1 text-right">
            @Html.DisplayNameFor(order => order.Date)
        </div>
        <div class="col-xs-3">
            @Model.Date
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 text-right">
            @Html.DisplayNameFor(order => order.Amount)
        </div>
        <div class="col-xs-3">
            @Model.Amount.ToString("C")
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 text-right">
            @Html.DisplayNameFor(order => order.StatusId)
        </div>
        <div class="col-xs-3">
            @Model.OrderStatus.Status
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 text-right">
            @Html.DisplayNameFor(order => order.CarId)
        </div>
        <div class="col-xs-3">
            @Html.ActionLink(Model.Car.VIN, "Details", "Cars", new { id = Model.CarId }, null)
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Details", "Clients", new { id = Model.Car.ClientId }, null)
</p>

Views/Orders/Edit.cshtml
@model ServiceStation.Models.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.CarId, "Car VIN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new {htmlAttributes = new {@class = "form-control", id = "datetimepicker1" } })
                @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"})
            </div>
        </div>

        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                    format: 'D MMM YYYY'
                });
            });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Clients", new { id = Model.Car.ClientId }, null)
</div>

@section Scripts {
    @Styles.Render("~/Content/bootstrap-datetimepicker.css")
    @Scripts.Render("~/scripts/moment.min.js")
    @Scripts.Render("~/scripts/bootstrap-datetimepicker.min.js")
}

Views/Orders/_OrdersList.cshtml
@model Tuple<IEnumerable<ServiceStation.Models.Order>, long, bool>

@{ bool parentIsClientDetails = Model.Item3; }

<div class="row">
    <div class="col-sm-1 text-center">
        @(parentIsClientDetails ? Html.ActionLink(" ", "Create", "Orders", new { clientId = Model.Item2 }, new { @class = "glyphicon glyphicon-plus"}) :
        Html.ActionLink(" ", "Create", "Orders", new { carId = Model.Item2 }, new { @class = "glyphicon glyphicon-plus"}))
    </div>
    <div class="col-sm-3">
        @Html.Label("Date")
    </div>
    <div class="col-sm-2">
        @Html.Label("Amount")
    </div>
    <div class="col-sm-3">
        @Html.Label("Status")
    </div>
    @if (Model.Item3)
    {
        <div class="col-sm-3">
            @Html.Label("Car VIN")
        </div>
    }
</div>

<hr />

@foreach (var order in Model.Item1)
{
    <div class="row">
        <div class="col-sm-1 text-center">
            @Html.ActionLink(" ", "Details", "Orders", new { id = order.id }, new { @class = "glyphicon glyphicon-info-sign" })
            @Html.ActionLink(" ", "Edit", "Orders", new { id = order.id }, new { @class = "glyphicon glyphicon-pencil", @style = "margin: 0px 5px 0px 5px" })
            @Html.ActionLink(" ", "Delete", "Orders", new { id = order.id }, new { @class = "glyphicon glyphicon-remove" })
        </div>
        <div class="col-sm-3">
            @Html.Label("", order.Date.ToString("D"))
        </div>
        <div class="col-sm-2">
            @Html.Label("", order.Amount.ToString("C"))
        </div>
        <div class="col-sm-3">
            @Html.Label("", order.OrderStatus.Status)
        </div>
        @if (parentIsClientDetails)
        {
            <div class="col-sm-3">
                <b>@Html.ActionLink(order.Car.VIN, "Details", "Cars", new { id = order.Car.id }, null)</b>
            </div>
        }
    </div>
}